#name: Build with jib
#on:
#  workflow_run:
#    workflows: ["Create dockerhub repository"]
#    branches: [master]
#    types:
#      - completed
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  build-image:
#    name: Build with jib
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out Git repository
#        uses: actions/checkout@v2
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
#      - name: Setup Maven Action
#        uses: s4u/setup-maven-action@v1.5.0
#        with:
#          java-version: 8
#          maven-version: 3.5.2
#
#      - run: mvn compile -f ./jib/pom.xml jib:build
#
#      - run: mvn compile -f ./jib/pom.xml jib:dockerBuild
