name: Build with jib
on:
  workflow_run:
    workflows: ["Create dockerhub repository"]
    branches: [master]
    types:
      - completed

jobs:
  build-image:
    name: Build with jib
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@3.5.2
        with:
          java-version: 8
          maven-version: 3.5.2

      - run: mvn compile jib:build

      - run: mvn compile jib:dockerBuild
