name: Security scan
on:
  workflow_run:
    workflows: ["Build and push"]
    branches: [master]
    types:
      - completed

jobs:
  scan:
    - name: Run Trivy vulnerability scanner in image mode
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'harshalk91/hello-world-spring-boot:latest'
        trivy-config: trivy.yaml



